apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
  labels:
    app: {{ .Release.Name }}-app
    version: "2.0"
    owner: IlyaBikmetov
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}-proj
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}-proj
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name : proj-web
          image: {{ .Values.container.appimage }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000