{
 "title": "MyApp",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Application_RPS_200_500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{service=\"app1-service\", uri=\"/api/v1/user/update\"}[2m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{service=\"app1-service\", uri=\"/api/v1/user/read\"}[2m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{service=\"app1-service\", status=\"200\"}[2m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{service=\"app1-service\", status=\"500\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx_RPS_200_500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_request_duration_seconds_count{exported_service=\"app1-service\"}[2m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(promhttp_metric_handler_requests_total{container=\"controller\", code=\"200\"}[2m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(promhttp_metric_handler_requests_total{container=\"controller\", code=\"500\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application_quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/update\"}[2m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/update\"}[2m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/update\"}[2m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/update\"}[2m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/read\"}[2m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/read\"}[2m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/read\"}[2m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/read\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx_quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.5\", container=\"controller\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes_CPU_MEM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "machine_memory_bytes", "legendFormat": "__auto" },
    { "expr": "system_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pg_database_size{datname=\"userdb\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_locks_count{datname=\"userdb\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_stat_activity_count{datname=\"userdb\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}