server:
  port: 8000
spring:
  datasource:
    generate-unique-name: false
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/parkingdb
    username: parking_user
    password: fdr43v32
microservices:
  money:
    url: http://money-service:8000
  dwh:
    url: http://dwh-service:8000
  places:
    url: http://places-service:8000