apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
    owner: IlyaBikmetov
data:
  POSTGRES_DB: parkingdb
  POSTGRES_USER: parking_user
  POSTGRES_PASSWORD: fdr43v32