apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: ingress
  name: nginx-ingress
  labels:
    team: devops
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
      - ingress
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s