apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    owner: IlyaBikmetov
    app: {{ .Release.Name }}-service
spec:
  selector:
    project: {{ .Release.Name }}-proj
  ports:
    - port: 8000
  type: NodePort