apiVersion: v1
data:
  application.yaml: "server:\r\n  port: 8000\r\nspring:\r\n  datasource:\r\n    generate-unique-name:
    false\r\n    driver-class-name: org.postgresql.Driver\r\n    url: jdbc:postgresql://postgres-service/parkingdb\r\n
    \   username: ${DATABASE_USERNAME}\r\n    password: ${DATABASE_PASSWORD}\r\n\r\nmicroservices:\r\n  money:
    \r\n    url: http://money-service:8000\r\n  dwh:\r\n    url: http://dwh-service:8000\r\n  places:
    \r\n    url: http://places-service:8000"
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config