apiVersion: v1
data:
  application.yaml: "server:\r\n  port: 8000\r\nspring:\r\n  datasource:\r\n    generate-unique-name:
    false\r\n    driver-class-name: org.postgresql.Driver\r\n    url: jdbc:postgresql://postgres-service/userdb\r\n
    \   username: ${DATABASE_USERNAME}\r\n    password: ${DATABASE_PASSWORD}\r\n\r\nmanagement:\r\n  endpoint:\r\n
    \   health:\r\n      show-details: always\r\n  metrics:\r\n    distribution:\r\n
    \     slo:\r\n        http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms,
    500ms\r\n    export:\r\n      enabled: true\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n
    \       include: \"*\""
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config