version: "3.3"
services:
  microservice-user:
    image: ilyabikmetov/microservice-user:3.0
    container_name: microservice-user
    ports:
      - "8000:8000"
    depends_on:
      - postgres-database

  microservice-order:
    image: ilyabikmetov/microservice-order:3.0
    container_name: microservice-order
    ports:
      - "8000:8000"
    depends_on:
      - postgres-database

  microservice-auth:
    image: ilyabikmetov/microservice-auth:2.0
    container_name: microservice-auth
    ports:
      - "8000:8000"

  microservice-echo:
    image: ilyabikmetov/microservice-echo:2.0
    container_name: microservice-echo
    ports:
      - "8000:8000"

  postgres-database:
    image: postgres:12.10
    container_name: postgres
    environment:
      POSTGRES_DB: "userdb"
      POSTGRES_USER: "login_users"
      POSTGRES_PASSWORD: "fdr43v32"
    ports:
      - "5432:5432"