create table if not exists users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username varchar(50) not null,
    firstName varchar(50) not null,
    lastName varchar(50) not null,
    email varchar(50),
    phone varchar(11)
);