server:
  port: 8004
spring:
  datasource:
    generate-unique-name: false
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/parkingdb
    username: parking_user
    password: fdr43v32
  kafka:
    bootstrap-servers: kafka:9092,localhost:29092