create table if not exists parking_status (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status varchar(50) not null
);

create table if not exists parking_place (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    place varchar(50),
    status_id bigint REFERENCES parking_status (id)
);

insert into parking_status(id, status) values (0, 'FREE');
insert into parking_status(id, status) values (1, 'BOOKING');
insert into parking_status(id, status) values (2, 'PARKING');

insert into parking_place(id, place, status_id) values (0, 'A1', 0);
insert into parking_place(id, place, status_id) values (1, 'A2', 0);
insert into parking_place(id, place, status_id) values (2, 'Parking1', 0);
insert into parking_place(id, place, status_id) values (3, 'Parking2', 0);