create table if not exists money (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(250) not null,
    money float not null,
    hold_money float,
    last_operation varchar(250) not null,
    last_value float,
    requestKey varchar(250) not null,
    updated timestamp not null
);