create table if not exists users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username varchar(250) not null,
    firstName varchar(250) not null,
    lastName varchar(250) not null,
    email varchar(50),
    phone varchar(50)
);