create table if not exists claims (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    place varchar(250) not null,
    requestKey varchar(250) not null,
    updated timestamp not null
);