create table if not exists parking (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(250) not null,
    place_id bigint not null,
    start timestamp,
    stop timestamp,
    money float,
    requestKey varchar(250) not null,
    updated timestamp not null
);