create table if not exists money (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(250) not null,
    money float not null,
    requestKey varchar(250) not null,
    updated timestamp not null
);