apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-job-parkingdb
spec:
  template:
    metadata:
      name:  postgres-init-parkingdb
      labels:
        app: init-postgresdb
    spec:
      containers:
        - image: postgres:12.10
          name: postgres-initdb
          command: [ "bin/sh", "-c", "PGPASSWORD=$DATABASE_PASSWORD psql -U $DATABASE_USER -d parkingdb -h postgres-service -a -f /app/migration/sqlCommand.sql" ]
          volumeMounts:
            - name: sql-command
              mountPath: "/app/migration"
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
      volumes:
        - name: sql-command
          configMap:
            name: sql-command
      restartPolicy: Never
---
apiVersion: v1
data:
  sqlCommand.sql: "create table if not exists parking (\r\n    id bigint PRIMARY KEY GENERATED BY DEFAULT
    AS IDENTITY,\r\n    username varchar(250) not null,\r\n    place_id bigint not null,
    \r\n    start timestamp,\r\n    stop timestamp,\r\n    money float,
    \r\n    requestKey varchar(250) not null,\r\n    updated timestamp not null);"
kind: ConfigMap
metadata:
  name: sql-command